### ISSUE TITLE
Unexpected result returned when selecting SHA-512

### ISSUE THREAD

**Issue by synth** [zonque/altcha-rails#3]
I'm just getting started with Altcha. The widget loads but when I click the checkbox, I get the following error "Unexpected result returned" and I'm not sure how to debug what might be wrong. Any help is appreciated!

![image](https://github.com/user-attachments/assets/d534795d-7346-4cb7-8867-a174893eb4e9)

UPDATE: This seems to occur when selecting SHA-512 as the algorithm.

**Comment by zonque** [comment]
Could you inspect the HTTP request and response in the browser's debug console? Do the rails logs show anything interesting? You can also add some debug prints in the response handlers to see what is being sent.

**Comment by synth** [comment]
Apologies, but we've had to abandon Altcha as we learned of the HTTPS requirement which is a blocker for us to adopt Altcha, so we're no longer able to test or provide debug info.

**Comment by zonque** [comment]
Okay, closing hence.
